implementation:
  - '(?i)(implement|implementation|solidity|contract)'

spec:
  - '(?i)(spec|definition|invariant|module)'

research:
  - '(?i)(analysis|research|paper|study)'

simulation:
  - '(?i)(simulation|model|modelling|twap|stress)'
